// flow-typed signature: be8f91f821ac10d69abb0f4e1f2e652f
// flow-typed version: <<STUB>>/eslint-config-samsao-base_v^2.0.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-samsao-base'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-samsao-base' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-samsao-base/rules/best-practices' {
  declare module.exports: any;
}

declare module 'eslint-config-samsao-base/rules/errors' {
  declare module.exports: any;
}

declare module 'eslint-config-samsao-base/rules/es6' {
  declare module.exports: any;
}

declare module 'eslint-config-samsao-base/rules/filenames' {
  declare module.exports: any;
}

declare module 'eslint-config-samsao-base/rules/imports' {
  declare module.exports: any;
}

declare module 'eslint-config-samsao-base/rules/style' {
  declare module.exports: any;
}

declare module 'eslint-config-samsao-base/rules/variables' {
  declare module.exports: any;
}

declare module 'eslint-config-samsao-base/test/no-react-reference.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-samsao-base/index' {
  declare module.exports: $Exports<'eslint-config-samsao-base'>;
}
declare module 'eslint-config-samsao-base/index.js' {
  declare module.exports: $Exports<'eslint-config-samsao-base'>;
}
declare module 'eslint-config-samsao-base/rules/best-practices.js' {
  declare module.exports: $Exports<'eslint-config-samsao-base/rules/best-practices'>;
}
declare module 'eslint-config-samsao-base/rules/errors.js' {
  declare module.exports: $Exports<'eslint-config-samsao-base/rules/errors'>;
}
declare module 'eslint-config-samsao-base/rules/es6.js' {
  declare module.exports: $Exports<'eslint-config-samsao-base/rules/es6'>;
}
declare module 'eslint-config-samsao-base/rules/filenames.js' {
  declare module.exports: $Exports<'eslint-config-samsao-base/rules/filenames'>;
}
declare module 'eslint-config-samsao-base/rules/imports.js' {
  declare module.exports: $Exports<'eslint-config-samsao-base/rules/imports'>;
}
declare module 'eslint-config-samsao-base/rules/style.js' {
  declare module.exports: $Exports<'eslint-config-samsao-base/rules/style'>;
}
declare module 'eslint-config-samsao-base/rules/variables.js' {
  declare module.exports: $Exports<'eslint-config-samsao-base/rules/variables'>;
}
declare module 'eslint-config-samsao-base/test/no-react-reference.test.js' {
  declare module.exports: $Exports<'eslint-config-samsao-base/test/no-react-reference.test'>;
}
