// flow-typed signature: 0b245e6eb6b4f16eaa194b28f4e5e3ef
// flow-typed version: <<STUB>>/eslint-config-samsao-node_v^2.0.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-samsao-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-samsao-node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-samsao-node/rules/env' {
  declare module.exports: any;
}

declare module 'eslint-config-samsao-node/test/no-react-reference.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-samsao-node/index' {
  declare module.exports: $Exports<'eslint-config-samsao-node'>;
}
declare module 'eslint-config-samsao-node/index.js' {
  declare module.exports: $Exports<'eslint-config-samsao-node'>;
}
declare module 'eslint-config-samsao-node/rules/env.js' {
  declare module.exports: $Exports<'eslint-config-samsao-node/rules/env'>;
}
declare module 'eslint-config-samsao-node/test/no-react-reference.test.js' {
  declare module.exports: $Exports<'eslint-config-samsao-node/test/no-react-reference.test'>;
}
